//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KetabGard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public decimal id { get; set; }
        public string Name { get; set; }
        public string Lastname { get; set; }
        public Nullable<decimal> Mcode { get; set; }
        public string Username { get; set; }
        public Nullable<decimal> Phonenumber { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> EducationDegree { get; set; }
        public string Picurl { get; set; }
    }
}
