//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KetabGard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public decimal Id { get; set; }
        public string Name { get; set; }
        public string Writer { get; set; }
        public string Editor { get; set; }
        public string Translator { get; set; }
        public Nullable<int> Genre { get; set; }
        public string YearofPublication { get; set; }
        public Nullable<decimal> GetCount { get; set; }
        public Nullable<bool> Here { get; set; }
        public Nullable<int> Row { get; set; }
        public Nullable<int> Col { get; set; }
        public Nullable<decimal> WhoIsGet { get; set; }
        public string WhenBack { get; set; }
        public Nullable<bool> Backed { get; set; }
        public Nullable<int> Rate { get; set; }
        public string WhoGiveRate { get; set; }
        public Nullable<decimal> Pages { get; set; }
        public Nullable<decimal> WhoSave { get; set; }
        public string PicURL { get; set; }
    }
}
