//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KetabGard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardTable
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PicURL { get; set; }
        public Nullable<decimal> SaveDateD { get; set; }
        public Nullable<int> CountOfGet { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<decimal> SaveDateM { get; set; }
        public Nullable<decimal> SaveDateY { get; set; }
        public string Name { get; set; }
        public decimal Id { get; set; }
        public decimal Expr1 { get; set; }
        public Nullable<decimal> LastBook { get; set; }
    }
}
