//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KetabGard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public decimal Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public Nullable<decimal> MdliCode { get; set; }
        public string Email { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> EducationDegree { get; set; }
        public string PicURL { get; set; }
        public Nullable<decimal> WhoSave { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<decimal> SaveDateD { get; set; }
        public string LastTimeComeDate { get; set; }
        public Nullable<int> CountOfGet { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> Acess { get; set; }
        public Nullable<decimal> BookId { get; set; }
        public string WhenGiveBook { get; set; }
        public string HowManyTimeForBook { get; set; }
        public Nullable<decimal> LastBook { get; set; }
        public Nullable<decimal> SaveDateM { get; set; }
        public Nullable<decimal> SaveDateY { get; set; }
        public Nullable<decimal> Expireactivate { get; set; }
        public string ActiveTime { get; set; }
        public string ExpireTime { get; set; }
    }
}
